// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9mS1IoHj_I0N28Futch91PnXyjYyT70',
    appId: '1:426946717348:web:0aad944dac7d07ea3ba831',
    messagingSenderId: '426946717348',
    projectId: 'athlor-27900',
    authDomain: 'athlor-27900.firebaseapp.com',
    storageBucket: 'athlor-27900.firebasestorage.app',
    measurementId: 'G-KY4N9J1YRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZMhLEdJ56YDU8MEdgNqgihnrdMD5Isw',
    appId: '1:426946717348:android:b71a9e176303ab7d3ba831',
    messagingSenderId: '426946717348',
    projectId: 'athlor-27900',
    storageBucket: 'athlor-27900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoyn4djUiJKIrohsoCETOqbkYcClQMT3o',
    appId: '1:426946717348:ios:5d65698f79da5b9b3ba831',
    messagingSenderId: '426946717348',
    projectId: 'athlor-27900',
    storageBucket: 'athlor-27900.firebasestorage.app',
    iosBundleId: 'com.athlor.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoyn4djUiJKIrohsoCETOqbkYcClQMT3o',
    appId: '1:426946717348:ios:5ac898402f35542f3ba831',
    messagingSenderId: '426946717348',
    projectId: 'athlor-27900',
    storageBucket: 'athlor-27900.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz9mS1IoHj_I0N28Futch91PnXyjYyT70',
    appId: '1:426946717348:web:0aad944dac7d07ea3ba831',
    messagingSenderId: '426946717348',
    projectId: 'athlor-27900',
    authDomain: 'athlor-27900.firebaseapp.com',
    storageBucket: 'athlor-27900.firebasestorage.app',
    measurementId: 'G-KY4N9J1YRN',
  );
}
